// SEI CERT C++
#include <stddef.h>

// DCL37-C-EX1

// NOTE: We will declare calloc instead of free, because free was defined in
// Noncompliant Code Example (Identifiers with External Linkage)

/* Not including stdlib.h */
void *calloc(size_t num, size_t size);  // UndCC_Valid

void func(void *ptr) {
  calloc(0, 0);
}


// DCL37-C-EX2

/* Sometimes generated by configuration tools such as autoconf */
#define const const  // UndCC_Valid

/* Allowed compilers with semantically equivalent extension behavior */
#define inline __inline  // UndCC_Valid


// DCL37-C-EX3

/*
  The following declarations of reserved identifiers exist in the glibc implementation of
  <stdio.h>. The original source code may be found at:
  https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=include/stdio.h;hb=HEAD
*/

#  define __need_size_t  // UndCC_Valid
#  include <stddef.h>
/* Generate a unique file name (and possibly open it).  */
extern int __path_search (char *__tmpl, size_t __tmpl_len,  // UndCC_Valid
              const char *__dir, const char *__pfx,  // UndCC_Valid
              int __try_tempdir);  // UndCC_Valid
